package com.korotkov.creditCRM.model.loansInfo;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
public class LoanInfoExpiredInfo {
    private LocalDate date;
    private Long totalIssuedLoanCount;
    private Double totalIssuedLoanAmount;
    private Long potentialIssuedLoanCount;
    private Long repeatIssuedLoanCount;
    private Double potentialIssuedLoanAmount;
    private Double repeatIssuedLoanAmount;
    private Long totalActiveLoanCount;
    private Long potentialActiveLoanCount;
    private Long repeatActiveLoanCount;
    private Long totalOn2DpdCount;
    private Long potentialOn2DpdCount;
    private Long repeatOn2DpdCount;
    private Double totalOn2DpdAmount;
    private Double potentialOn2DpdAmount;
    private Double repeatOn2DpdAmount;
    private Long totalOn5DpdCount;
    private Long potentialOn5DpdCount;
    private Long repeatOn5DpdCount;
    private Double totalOn5DpdAmount;
    private Double potentialOn5DpdAmount;
    private Double repeatOn5DpdAmount;
    private Long totalOn10DpdCount;
    private Long potentialOn10DpdCount;
    private Long repeatOn10DpdCount;
    private Double totalOn10DpdAmount;
    private Double potentialOn10DpdAmount;
    private Double repeatOn10DpdAmount;
    private Long totalOn15DpdCount;
    private Long potentialOn15DpdCount;
    private Long repeatOn15DpdCount;
    private Double totalOn15DpdAmount;
    private Double potentialOn15DpdAmount;
    private Double repeatOn15DpdAmount;
    private Long totalOn20DpdCount;
    private Long potentialOn20DpdCount;
    private Long repeatOn20DpdCount;
    private Double totalOn20DpdAmount;
    private Double potentialOn20DpdAmount;
    private Double repeatOn20DpdAmount;
    private Long totalOn25DpdCount;
    private Long potentialOn25DpdCount;
    private Long repeatOn25DpdCount;
    private Double totalOn25DpdAmount;
    private Double potentialOn25DpdAmount;
    private Double repeatOn25DpdAmount;
    private Long totalOn30DpdCount;
    private Long potentialOn30DpdCount;
    private Long repeatOn30DpdCount;
    private Double totalOn30DpdAmount;
    private Double potentialOn30DpdAmount;
    private Double repeatOn30DpdAmount;
    private Long totalOn40DpdCount;
    private Long potentialOn40DpdCount;
    private Long repeatOn40DpdCount;
    private Double totalOn40DpdAmount;
    private Double potentialOn40DpdAmount;
    private Double repeatOn40DpdAmount;
    private Long totalOn50DpdCount;
    private Long potentialOn50DpdCount;
    private Long repeatOn50DpdCount;
    private Double totalOn50DpdAmount;
    private Double potentialOn50DpdAmount;
    private Double repeatOn50DpdAmount;
    private Long totalOn60DpdCount;
    private Long potentialOn60DpdCount;
    private Long repeatOn60DpdCount;
    private Double totalOn60DpdAmount;
    private Double potentialOn60DpdAmount;
    private Double repeatOn60DpdAmount;
    private Long totalOn90DpdCount;
    private Long potentialOn90DpdCount;
    private Long repeatOn90DpdCount;
    private Double totalOn90DpdAmount;
    private Double potentialOn90DpdAmount;
    private Double repeatOn90DpdAmount;
    private Long totalOn120DpdCount;
    private Long potentialOn120DpdCount;
    private Long repeatOn120DpdCount;
    private Double totalOn120DpdAmount;
    private Double potentialOn120DpdAmount;
    private Double repeatOn120DpdAmount;
    private Long totalOn150DpdCount;
    private Long potentialOn150DpdCount;
    private Long repeatOn150DpdCount;
    private Double totalOn150DpdAmount;
    private Double potentialOn150DpdAmount;
    private Double repeatOn150DpdAmount;
    private Long totalOn180DpdCount;
    private Long potentialOn180DpdCount;
    private Long repeatOn180DpdCount;
    private Double totalOn180DpdAmount;
    private Double potentialOn180DpdAmount;
    private Double repeatOn180DpdAmount;
    private Long totalOn250DpdCount;
    private Long potentialOn250DpdCount;
    private Long repeatOn250DpdCount;
    private Double totalOn250DpdAmount;
    private Double potentialOn250DpdAmount;
    private Double repeatOn250DpdAmount;
    private Long totalOn300DpdCount;
    private Long potentialOn300DpdCount;
    private Long repeatOn300DpdCount;
    private Double totalOn300DpdAmount;
    private Double potentialOn300DpdAmount;
    private Double repeatOn300DpdAmount;
    private Long totalOn500DpdCount;
    private Long potentialOn500DpdCount;
    private Long repeatOn500DpdCount;
    private Double totalOn500DpdAmount;
    private Double potentialOn500DpdAmount;
    private Double repeatOn500DpdAmount;
}
