package com.korotkov.mainCurrentApp.enums;

public enum ApplicationStatusesCRMEnum {
    APPROVED,
    CANCELED_BY_CLIENT,
    CANCELED_BY_SYSTEM,
    CONFIRMED_BY_CLIENT,
    INITIAL,
    MAKE_DECISION_IN_PROGRESS,
    OUTGOING_PAYMENT_CANCELED,
    OUTGOING_PAYMENT_ERROR,
    OUTGOING_PAYMENT_SUCCEED,
    REJECTED,
    SENT_TO_CLIENT_FOR_REVISION,
    SENT_TO_UNDERWRITING,
    UNDERWRITING_IN_PROGRESS
}
