package com.korotkov.mainCurrentApp.enums;

public enum ReportNameEnum {
    MAIN_DAILY_REPORT,
    COLLECTION_COMMON_DATA_WITH_ASSIGNED_COLLECTOR_REPORT,
    PRE_SOFT_COLLECTION_BONUS_REPORT,
    STAGES_WITH_ASSIGNED_BONUS_REPORT,
    PAYMENTS_EXPORT_WITH_PAID_FEES,
    PAYMENTS_EXPORT_WITH_PAID_FEES_INCORRECT,
    CLIENT_DOCUMENTS_EXPORT_FOR_CHECK_INSURANCE,
    LOANS_INFO_EXPIRED_INFO_REPORT,
    PTP_PRESOFT_RESULTED_CALLS,
    APPS_AND_LOANS_WITH_SOURCE,
    EXPORT_APP_LIST_WITH_SOURCE,
    EXPORT_LOAN_LIST_WITH_SOURCE,
    EXPORT_LOAN_AND_PAYMENT_BY_DATE_FOR_CROSS_CHECKING,
    EXPORT_LOAN_BY_DATE_AND_HOUR,
    EXPORT_PAYMENT_BY_DATE_AND_HOUR,
    EXPORT_UNDERWRITERS_RESULTS,
    EXPORT_APPS_BY_UNDERWRITERS,
    APP_BY_UNDERWRITER_PER_HOUR,
    EXPORT_RESULTS_OF_APPLICATION_BY_DATE,
    EXPORT_LIST_REFUND_OVERPAYMENTS,
    EXPORT_LIST_DEACTIVATED_PAYMENTS,
    EXPORT_LIST_ACTIVE_PAYMENTS,
    EXPORT_LIST_PHONE_NUMBERS_OF_PASSIVE_CLIENTS_FOR_SMS,
    EXPORT_LIST_ISSUED_LOAN,
    BIG_REPORT_COLLECTION_PAYMENT
}
