package com.korotkov.mainCurrentApp.enums;

public enum ScheduledTaskName {
    CURRENCY_RATE_UPDATING,
    MAIN_DAILY_REPORT_EMAILING,
    EMAILS_REJECTED_TRAFFIC_REGISTERED_CLIENT_NO_APP,
    EMAILS_REJECTED_TRAFFIC_PASSIVE_CLIENT,
    EMAILS_REJECTED_TRAFFIC_EXPIRED_LOANS,
    EMAILS_REJECTED_TRAFFIC_REJECTED_APPLICATIONS,
    EMAILS_REJECTED_TRAFFIC_CANCELED_BY_SYSTEM_APPLICATIONS,
    EMAILS_REJECTED_TRAFFIC_CANCELED_BY_CLIENT_APPLICATIONS
}
