package com.korotkov.mainCurrentApp.enums;

public enum ScheduledCheckingTitleEnum {
    APPLICATION_ON_LONG_DMS,
    CHECK_CREATING_DEBT_COLLECTION,
    CHECK_CALCULATION_ALL_LOANS,
    CHECK_TIME_LAST_APPLICATION,
    CHECK_TIME_LAST_LOAN,
    CHECK_TIME_LAST_REGISTERED_CLIENT,
    CHECK_TIME_LAST_PAYMENT,
    CHECK_APPS_WITH_PAYOUT_ERROR
}
